// FIGURE index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, HP, SPEED, *, *, *
ITEM( 0, 0, "0", "Figure", "0", "SAS support", "...", "icon_body_e_sas_supp", "1", "0", "0", "60", "60", "*", "*", "*" )
ITEM( 1, 0, "1", "Figure", "1", "Ada Wong", "...", "icon_body_e_ada", "1", "0", "0", "10", "80", "*", "*", "*" )
ITEM( 2, 0, "2", "Figure", "2", "Nico", "...", "icon_body_e_nico", "1", "0", "0", "40", "50", "*", "*", "*" )

// WEAPON index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, ACCURACY, DAMAGE, RANGE, FIRE RATE, MOBILITY
ITEM( 0, 0, "20", "Weapon", "20", "BERETTA", "PERKS_SEMIAUTOMATIC_WITH_A", "weapon_m9beretta", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 1, 0, "21", "Weapon", "21", "COLT1911", "PERKS_SEMIAUTOMATIC_WITH_MEDIUM", "weapon_colt_45", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 2, 0, "22", "Weapon", "22", "USP", "PERKS_SEMIAUTOMATIC_WITH_MEDIUM1", "weapon_usp_45", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 3, 0, "23", "Weapon", "23", "DESERTEAGLE", "PERKS_SEMIAUTOMATIC_WITH_HIGH", "weapon_desert_eagle", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 4, 0, "24", "Weapon", "24", "DESERTEAGLEGOLD", "PERKS_GOLD_PLATED_SEMIAUTOMATIC", "weapon_desert_eagle_gold", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 5, 0, "25", "Weapon", "25", "SA1911", "...", "weapon_sa1911", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 6, 0, "26", "Weapon", "26", "MK22", "...", "weapon_mk22", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 7, 0, "27", "Weapon", "27", "Five 7", "...", "weapon_five7", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 8, 0, "28", "Weapon", "28", "Kimber", "...", "weapon_kimber", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 9, 0, "29", "Weapon", "29", "T850", "...", "weapon_taurus", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 10, 0, "30", "Weapon", "30", "Magnum", "...", "weapon_mw2_magnum", "1", "0", "0", "100", "100", "100", "100", "100" )
ITEM( 11, 0, "31", "Weapon", "31", "Glock", "...", "weapon_glock", "1", "0", "0", "100", "100", "100", "100", "100" )

// FIRSTPERK index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, *, *, *, *, *
ITEM( 0, 0, "40", "FirstPerk", "40", "STOPPING_POWER", "PERKS_INCREASED_BULLET_DAMAGE", "specialty_bulletdamage", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 1, 0, "41", "FirstPerk", "41", "SONIC_BOOM", "PERKS_HIGHER_EXPLOSIVE_WEAPON", "specialty_explosivedamage", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 2, 0, "42", "FirstPerk", "42", "DEEP_IMPACT", "PERKS_DEEPER_BULLET_PENETRATION", "specialty_bulletpenetration", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 3, 0, "43", "FirstPerk", "43", "STEADY_AIM", "PERKS_INCREASED_HIPFIRE_ACCURACY", "specialty_bulletaccuracy", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 4, 0, "44", "FirstPerk", "44", "DOUBLE_TAP", "PERKS_INCREASED_RATE_OF_FIRE", "specialty_rof", "1", "0", "0", "*", "*", "*", "*", "*" )

// SECONDPERK index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, *, *, *, *, *
ITEM( 0, 0, "60", "SecondPerk", "60", "EXTREME_CONDITIONING", "PERKS_SPRINT_FOR_LONGER_DISTANCES", "specialty_longersprint", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 1, 0, "61", "SecondPerk", "61", "SLEIGHT_OF_HAND", "PERKS_FASTER_RELOADING", "specialty_fastreload", "1", "0", "0", "*", "*", "*", "*", "*" )

// THIRDPERK index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, *, *, *, *, *
ITEM( 0, 0, "80", "ThirdPerk", "80", "Night Vision", "...", "hud_icon_nvg", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 1, 0, "81", "ThirdPerk", "81", "BANDOLIER", "PERKS_EXTRA_AMMUNITION_MAGAZINES", "specialty_extraammo", "1", "0", "0", "*", "*", "*", "*", "*" )

/*
// new perky
 - 1 - dve zbrane
 - 3 - pokladanie ammo na zem
 - 3 - obv‰zy - oûivovanie seba aj ostatn˝ch
 - 2 - last stand + moûnosù byù oûiven˝ in˝m hr·Ëom
 - 3 - repelent gran·t
 - 2 - zobrazovanie zost·vaj˙ceho zdravia ako u prek·ûok
 - 3 - 
 
*/