#ifdef TAB_X
	#undef TAB_X
	#undef TAB_Y
	#undef TAB_W
	#undef TAB_H

	#undef TAB_VIS

	#undef TAB_ORIENT
	#undef TAB_BORDER

	#undef TAB_BUTTONS
	#undef TAB_SEPARATORS

	#undef TAB_SEP_0
	#undef TAB_SEP_1
	#undef TAB_SEP_2
	#undef TAB_SEP_3
	#undef TAB_SEP_4

	#undef TAB_SELECTED_DVAR
	
	#undef TAB_ITEM_X
	#undef TAB_ITEM_Y
	#undef TAB_SEPARATOR_SIZE
	#undef TAB_ITEM_HORIZONTAL_X
	#undef TAB_ITEM_HORIZONTAL_Y
	#undef TAB_ITEM_VERTICAL_X
	#undef TAB_ITEM_VERTICAL_Y
#endif