// FIGURE index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, HP, SPEED, *, *, *
ITEM( 0, 0, "0", "Figure", "100", "Skulls", "...", "icon_body_m_skulls", "1", "0", "0", "60", "50", "*", "*", "*" )
ITEM( 1, 0, "1", "Figure", "101", "Max", "...", "icon_body_m_max", "1", "0", "0", "40", "80", "*", "*", "*" )
ITEM( 2, 0, "2", "Figure", "102", "Raam", "...", "icon_body_m_raam", "1", "0", "0", "100", "10", "*", "*", "*" )

// WEAPON index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, DMG, RANGE, FIRE RATE, *, *
// fire rate(100%) quickRaiseTime = 0.25
// fire rate(0%) quickRaiseTime = 2
ITEM( 0, 0, "20", "Weapon", "120", "Classic", "...", "clear_alpha_stencil", "1", "0", "0", "30", "10", "100", "*", "*" )
ITEM( 1, 0, "21", "Weapon", "121", "Shovel", "...", "clear_alpha_stencil", "1", "0", "0", "10", "100", "70", "*", "*" )
ITEM( 2, 0, "22", "Weapon", "122", "Axe", "...", "clear_alpha_stencil", "1", "0", "0", "60", "80", "60", "*", "*" )
ITEM( 3, 0, "23", "Weapon", "123", "Throwing", "...", "clear_alpha_stencil", "1", "0", "0", "30", "10", "100", "*", "*" )
ITEM( 4, 0, "24", "Weapon", "124", "Katana", "...", "clear_alpha_stencil", "1", "0", "0", "100", "80", "40", "*", "*" )
ITEM( 5, 0, "25", "Weapon", "125", "Ballistic", "...", "clear_alpha_stencil", "1", "0", "0", "50", "20", "100", "*", "*" )

// FIRSTPERK index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, *, *, *, *, *
ITEM( 0, 0, "40", "FirstPerk", "140", "Health Pack", "Add 5% health.", "clear_alpha_stencil", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 1, 0, "41", "FirstPerk", "141", "Speed Pack", "Add 5% speed.", "clear_alpha_stencil", "1", "0", "0", "*", "*", "*", "*", "*" )
ITEM( 2, 0, "42", "FirstPerk", "142", "Meat Man", "Maximizes knife damage.", "clear_alpha_stencil", "1", "0", "0", "*", "*", "*", "*", "*" )

// SECONDPERK index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, *, *, *, *, *
ITEM( 0, 0, "60", "SecondPerk", "160", "PERK_NONE", "PERK_NONE", "clear_alpha_stencil", "1", "0", "0", "*", "*", "*", "*", "*" )

// THIRDPERK index, page, lineIndex, type, stat, name, info, icon, perm, xp, rank, *, *, *, *, *
ITEM( 0, 0, "80", "ThirdPerk", "180", "PERK_NONE", "PERK_NONE", "clear_alpha_stencil", "1", "0", "0", "*", "*", "*", "*", "*" )

/*
// new perky
 - 3 - stavanie spawnu
 - 2 - poison
 - 2 - konštantné menovky nad hráèom
 - 3 - privolanie botov
 - 3 - speed hack - doèasné zvýšenie doby šprintu
 - 3 - night vision pre zombie
 - 3 - zmrazenie hráèa
 - 2 - no respawn - zmeníš sa na zombie hneï na mieste
 
*/