#define COLOR_TRANSPARENT		0 0 0 0

#define COLOR_BG_FILL 			0 0 0 1
#define COLOR_BG_TRANSPARENT 	0.5 0.5 0.5 0.5

#define COLOR_FG_FILL 			1 0 0 1
#define COLOR_FG_SELECTED 		1 0 0 0.6
#define COLOR_FG_HIGHLIGHT 		1 0 0 0.3

#define COLOR_FG_PROGRESSBAR 1 0 0 0.3
#define COLOR_FG_PROGRESSBAR_INC 0 1 0 0.3

// http://www.tayloredmktg.com/rgb/
#define COLOR_WHITE				1 1 1 1
#define COLOR_BLACK				0 0 0 1

#define COLOR_RED 				1 0 0 1
#define COLOR_GREEN 			0 1 0 1
#define COLOR_BLUE 				0 0 1 1
#define COLOR_YELLOW 			1 1 0 1
#define COLOR_CYAN 				0 1 1 1
#define COLOR_MAGENTA 			1 0 1 1

#define COLOR_ORANGE			1 0.65 0 1

#define COLOR_SHADER_OFF		1 1 1 0.5
#define COLOR_SHADER_HIGHLIGHT	1 1 1 0.9
#define COLOR_SHADER_SELECTED	1 1 1 1

// 0.0208 = 1px
#define FONTSCALE_6		0.1248
#define FONTSCALE_7		0.1456
#define FONTSCALE_8		0.1664
#define FONTSCALE_9		0.1872
#define FONTSCALE_10	0.2080
#define FONTSCALE_11	0.2288
#define FONTSCALE_12	0.2496
#define FONTSCALE_13	0.2704
#define FONTSCALE_14	0.2912
#define FONTSCALE_16	0.3328
#define FONTSCALE_18	0.3744
#define FONTSCALE_20	0.4160
#define FONTSCALE_22	0.4576
#define FONTSCALE_24	0.4992
#define FONTSCALE_26	0.5408
#define FONTSCALE_28	0.5824
#define FONTSCALE_30	0.6240
#define FONTSCALE_32	0.6656
#define FONTSCALE_34	0.7072
#define FONTSCALE_36	0.7488
#define FONTSCALE_38	0.7904
#define FONTSCALE_40	0.8320